version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: architecture-map-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
