name: Deploy
run-name: ${{ github.actor }} - test deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project directory
        uses: actions/checkout@v3
      - name: Use Node.js 16.16
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
      - name: Build the app
        run: |
          npm i
          npm run build
          mkdir dist 
          mv build dist 
          mv package.json dist/package.json
          mv package-lock.json dist/package-lock.json
          cd dist
          npm ci --omit dev
          npx prisma generate
          ls -ahl
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          retention-days: 1
          path: dist

  deploy-job:
    needs: build
    runs-on: ubuntu-latest
    environment: linode
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: move all to one folder
        run: |
          mkdir dist
          cp -r node_modules/.  dist/node_modules
          mv build dist/build
          mv package.json dist/package.json
          mv package-lock.json dist/package-lock.json
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /var/www/architecture-map
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRV_KEY}}
          rmRemote: true
